/**
 * Converts db_json/foodies/*.json  →  apps/backend/db/seed.sql
 *
 * Usage (from monorepo root):
 *   node apps/backend/db/json-to-seed.mjs
 *
 * Default password for seed users: Foodies2025!
 * (bcrypt hash below — regenerate with bcrypt.hashpw if needed)
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const JSON_DIR = path.resolve(__dirname, '../../../db_json/foodies');
const OUT_FILE = path.resolve(__dirname, 'seed.sql');

const DEFAULT_HASH = '$2b$10$Qu5kzEeyZ2M6qUHwsGgBSeiepKq4pupwauLUv0pf/s/Aa51g.p5Jy';

const esc = (v) => {
  if (v === null || v === undefined) return 'NULL';
  return `'${String(v).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
};

const oid = (v) => (v && typeof v === 'object' && '$oid' in v ? v['$oid'] : v);

const read = (name) => {
  const file = path.join(JSON_DIR, `${name}.json`);
  if (!fs.existsSync(file)) { console.warn(`  ⚠  ${name}.json not found — skipping`); return null; }
  return JSON.parse(fs.readFileSync(file, 'utf8'));
};

const lines = [
  '-- Auto-generated by json-to-seed.mjs — do not edit manually',
  `-- Generated: ${new Date().toISOString()}`,
  '-- Default password for seed users: Foodies2025!',
  'USE headliner_db;',
  '',
];

// ── categories ───────────────────────────────────────────────────
const categories = read('categories');
if (categories) {
  const rows = categories.map((c) => `(${esc(c.name)})`).join(',\n  ');
  lines.push(`-- categories (${categories.length})`);
  lines.push(`INSERT IGNORE INTO categories (name) VALUES\n  ${rows};\n`);
}

// ── ingredients ──────────────────────────────────────────────────
const ingredients = read('ingredients');
if (ingredients) {
  lines.push(`-- ingredients (${ingredients.length})`);
  const all = ingredients.map((i) =>
    `(${esc(oid(i._id))}, ${esc(i.name)}, ${esc(i.desc ?? '')}, ${esc(i.img ?? '')})`,
  );
  const CHUNK = 100;
  for (let s = 0; s < all.length; s += CHUNK) {
    lines.push(`INSERT IGNORE INTO ingredients (id, name, \`desc\`, img) VALUES\n  ${all.slice(s, s + CHUNK).join(',\n  ')};`);
  }
  lines.push('');
}

// ── seed users ───────────────────────────────────────────────────
const rawUsers = read('users');
const oidToMysqlId = {};
if (rawUsers) {
  lines.push(`-- seed users (${rawUsers.length})  password: Foodies2025!`);
  const rows = rawUsers.map((u, idx) => {
    oidToMysqlId[oid(u._id)] = idx + 1;
    return `(${esc(u.name ?? 'User')}, ${esc(u.email ?? `user${idx + 1}@example.com`)}, ${esc(DEFAULT_HASH)}, ${esc(u.avatar ?? null)})`;
  });
  lines.push(`INSERT IGNORE INTO users (name, email, password, avatar) VALUES\n  ${rows.join(',\n  ')};\n`);
}

// ── recipes + recipe_ingredients ─────────────────────────────────
const recipes = read('recipes');
if (recipes) {
  lines.push(`-- recipes (${recipes.length}) + recipe_ingredients`);
  lines.push('SET @recipe_id = 0;');
  for (const r of recipes) {
    const ownerMysqlId = oidToMysqlId[oid(r.owner)] ?? 1;
    lines.push(
      `INSERT IGNORE INTO recipes (title, category, owner_id, area, calories, instructions, description, thumb, time) VALUES ` +
      `(${esc(r.title)}, ${esc(r.category)}, ${ownerMysqlId}, ${esc(r.area ?? null)}, ` +
      `${esc(r.calories ?? null)}, ${esc(r.instructions)}, ${esc(r.description)}, ` +
      `${esc(r.thumb ?? null)}, ${esc(String(r.time ?? ''))});`,
    );
    lines.push('SET @recipe_id = LAST_INSERT_ID();');
    for (const ing of r.ingredients ?? []) {
      lines.push(
        `INSERT IGNORE INTO recipe_ingredients (recipe_id, ingredient_id, measure) ` +
        `VALUES (@recipe_id, ${esc(oid(ing.id))}, ${esc(ing.measure ?? '')});`,
      );
    }
  }
  lines.push('');
}

fs.writeFileSync(OUT_FILE, lines.join('\n'), 'utf8');
console.log(`✅  seed.sql written → ${OUT_FILE}`);
